config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  devise_for :users
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  mount_uploader :cover, CoverUploader
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@posts = Post.order(created_at: :desc)
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  require 'parse-ruby-client'
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        client = Parse.init(application_id: 'QB8MVuvXQTw9PDZ7VEjv03d3RheH7Y4FMfZCXkoE', api_key: 'pX3KupGw1xnzautQEXvzM3ljlBdte5h3MDy5TiM7')
        data = { :alert => "One article titled '#{post_params[:title]}' has been released" }
        push = Parse::Push.new(data, "Anokri")
        push.save
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :cover, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Blog
    meta name="keywords" content="This is example blog"
    meta name="author" content='Alif Jamaluddin'

    link rel="icon" type="image/png" href="favicon.ico"
    
    = javascript_include_tag \
   	"application"
   	= stylesheet_link_tag \
   	"application"
   	link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" type="text/css"
   	link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" type="text/css"
   	= csrf_meta_tags


body
== render 'share/navbar'

= yield

== render 'share/footer'



   

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.slim
header.intro-header style=("background-image: url('home-bg.jpg')") 
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .site-heading
          h1 Alif Jamaluddin
          hr.small/
          span.subheading Example Blog by Alif Jamaluddin
p#notice = notice 

.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      
      - @posts.each do |post| 
        .post-preview
            a = link_to post 
              h2.post-title = post.title
              h3.post-subtitle = post.content.truncate(50, separator: ' ')
              p.post-meta
                | Posted by 
                a href="#"  = post.user.profile.name
                =  post.created_at.strftime(" on %B %d, %Y") 
            hr/


      

     
      /! Pager
      ul.pager
        li.next
          a href="#"  Older Posts &rarr;

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.text_field :cover %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Cover</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.cover %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.slim
p.notice = notice


header.intro-header style=("background-image: url('../../post-bg.jpg')") 
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .post-heading
          h1  
            = @post.title 

          /h2.subheading Problems look mighty small from 150 miles up
          span.meta
            | Posted by 
            a href="#"  = @post.user.profile.name
            = @post.created_at.strftime(" on %B %d, %Y") 
article
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        = @post.content
        
        hr

        .profile
          a = link_to @post
            img.avatar src="#{@post.user.profile.avatar}" 
          h5 = @post.user.profile.name
          small = @post.user.profile.bio

app/views/share/_footer.html.slim
hr/
/! Footer
footer
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        ul.list-inline.text-center
          li
            a href="#" 
              span.fa-stack.fa-lg
                i.fa.fa-circle.fa-stack-2x
                i.fa.fa-twitter.fa-stack-1x.fa-inverse
          li
            a href="#" 
              span.fa-stack.fa-lg
                i.fa.fa-circle.fa-stack-2x
                i.fa.fa-facebook.fa-stack-1x.fa-inverse
          li
            a href="#" 
              span.fa-stack.fa-lg
                i.fa.fa-circle.fa-stack-2x
                i.fa.fa-github.fa-stack-1x.fa-inverse
        p.copyright.text-muted Copyright &copy; Your Website 2014

app/views/share/_navbar.html.slim
nav.navbar.navbar-default.navbar-custom.navbar-fixed-top
  .container-fluid
    .navbar-header.page-scroll
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      =link_to 'AJ Blog', root_path, {:class=>'navbar-brand'} 
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Home', pages_home_path
        li
          = link_to 'About', pages_about_path
        li
          = link_to 'Contact', pages_contact_path
          